# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
